costs_functions = {@(x)sistema_01(x), @(x)sistema_02(x), @(x)sistema_03(x), ...
    @(x)sistema_04(x), @(x)sistema_05(x), @(x)sistema_06(x), ...
    @(x)sistema_07(x), @(x)sistema_08(x), @(x)sistema_09(x), ...
    @(x)sistema_10(x), @(x)sistema_11(x), @(x)sistema_12(x), ...
    @(x)sistema_13(x), @(x)sistema_14(x), @(x)sistema_15(x), ...
    @(x)sistema_16(x), @(x)sistema_17(x), @(x)sistema_18(x), ...
    @(x)sistema_19(x), @(x)sistema_20(x), @(x)sistema_21(x), ...
    @(x)sistema_22(x), @(x)sistema_23(x), @(x)sistema_24(x), ...
    @(x)sistema_25(x), @(x)sistema_26(x), @(x)sistema_27(x), ...
    @(x)sistema_28(x), @(x)sistema_29(x), @(x)sistema_30(x), ...
    @(x)sistema_31(x), @(x)sistema_32(x), @(x)sistema_33(x), ...
    @(x)sistema_34(x), @(x)sistema_35(x), @(x)sistema_36(x), ...
    @(x)sistema_37(x), @(x)sistema_38(x), @(x)sistema_39(x)};

num_vars = [];
for f = 1:39
    cost_function = costs_functions{f};
    funciono = 0;
    for i = 1:30
        try
            cost_function(0.5 * ones(1,i));
            num_vars = [num_vars, i];
            funciono = 1;
        catch
        end
        if funciono
            break
        end
    end
end
